# General Application Settings
spring.application.name=MVCSpringboot
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
# Ensure data.sql is executed
spring.sql.init.mode=always

# Postgres (Neon Tech) Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-still-breeze-adqcu74m-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VRf8HY9sXbLC
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# H2 Database Configuration (DISABLED)
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2