spring.application.name=Taller2SpringBoot

#Update makes it so every start of the app it cleans the tables
spring.jpa.hibernate.ddl-auto=update
#JDBC component that connects java to DB
spring.datasource.driver-class-name=org.h2.Driver
#dialect determines variables, etc
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#So data insertion waits for the table to be created
spring.jpa.defer-datasource-initialization=true


#url of the db
spring.datasource.url=jdbc:h2:mem:testdb
#Username
spring.datasource.username=sa
#Password
spring.datasource.password=

#Activate H2 console
spring.h2.console.enabled=true
#url to get to the h2
spring.h2.console.path=/h2

#So it shows the query that is done behind the scenes from query methods
spring.jpa.show-sql=true